# Generated by Django 3.2.3 on 2021-05-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_auto_20210530_1129'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.degree_batch'),
        ),
        migrations.DeleteModel(
            name='Degree_Batch',
        ),
    ]
