# Generated by Django 3.2.3 on 2021-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('file', models.FileField(upload_to='notices/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
